//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aire
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class allcopoy1 : DbContext
    {
        public allcopoy1()
            : base("name=allcopoy1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comprGOOGLCOPY1> comprGOOGLCOPY1 { get; set; }
        public virtual DbSet<comprskyCOPY1> comprskyCOPY1 { get; set; }
        public virtual DbSet<tablXCOPY1> tablXCOPY1 { get; set; }
    }
}
