//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aire
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprGOOGL2Days
    {
        public int id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string citys { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<double> Olde_price { get; set; }
        public Nullable<double> New_price { get; set; }
        public Nullable<double> Difference { get; set; }
        public Nullable<double> Cheapest { get; set; }
        public string Cabin { get; set; }
        public string web { get; set; }
    }
}
