//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aire
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class domestic : DbContext
    {
        public domestic()
            : base("name=domestic")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comprGOOGL14Days> comprGOOGL14Days { get; set; }
        public virtual DbSet<comprGOOGL2Days> comprGOOGL2Days { get; set; }
        public virtual DbSet<comprGOOGL3Days> comprGOOGL3Days { get; set; }
        public virtual DbSet<comprGOOGL4Days> comprGOOGL4Days { get; set; }
        public virtual DbSet<comprsky14Days> comprsky14Days { get; set; }
        public virtual DbSet<comprsky2Days> comprsky2Days { get; set; }
        public virtual DbSet<comprsky3Days> comprsky3Days { get; set; }
        public virtual DbSet<comprsky4Days> comprsky4Days { get; set; }
    }
}
