//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aire
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GFEntities18 : DbContext
    {
        public GFEntities18()
            : base("name=GFEntities18")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comprGOOGLBusiness> comprGOOGLBusinesses { get; set; }
        public virtual DbSet<comprGOOGLPremium> comprGOOGLPremiums { get; set; }
    }
}
