//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aire
{
    using System;
    using System.Collections.Generic;
    
    public partial class t
    {
        public int id { get; set; }
        public string From { get; set; }
        public string Via { get; set; }
        public string To { get; set; }
        public string citys { get; set; }
        public string Airlin { get; set; }
        public Nullable<double> Olde_price { get; set; }
        public Nullable<double> New_price { get; set; }
        public Nullable<double> Difference { get; set; }
        public Nullable<double> Cheapest { get; set; }
        public Nullable<double> Total_Tax { get; set; }
        public Nullable<double> Total_amount { get; set; }
        public string Class { get; set; }
        public string Dates { get; set; }
        public string Cabin { get; set; }
        public Nullable<double> TAX1 { get; set; }
        public string Tcode1 { get; set; }
        public Nullable<double> TAX2 { get; set; }
        public string Tcode2 { get; set; }
        public Nullable<double> TAX3 { get; set; }
        public string Tcode3 { get; set; }
        public string Farebasis { get; set; }
        public string Season { get; set; }
    }
}
