//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aire
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablXCOPY
    {
        public int id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string citys { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<double> Old_prie_Google { get; set; }
        public Nullable<double> New_prie_Google { get; set; }
        public Nullable<double> Difference_Google { get; set; }
        public Nullable<double> Cheapest_filght { get; set; }
        public string Web_Google { get; set; }
        public string Cabin_filght { get; set; }
        public Nullable<double> Old_prie_Skyscanner { get; set; }
        public Nullable<double> New_prie_Skyscanner { get; set; }
        public Nullable<double> Difference_Skyscanner { get; set; }
        public Nullable<double> Cheapest_Skyscanner { get; set; }
        public string Web_Skyscanner { get; set; }
        public string Cabin_skayscanner { get; set; }
    }
}
